[fix] Updated build scripts

diff --git a/scripts/systemd b/scripts/systemd
--- a/scripts/systemd
+++ b/scripts/systemd
@@ -8,7 +8,39 @@ BLUE='\033[0;34m'
 RED='\033[0;31m'
 NC='\033[0m'
 
+GO_VERSION="1.24.0"
+
 HOME="$(git rev-parse --show-toplevel)"
+FILE_GO_HTTP="cmd/server/main.go"
+
+if ! command -v go &>/dev/null; then
+    echo -e "${YELLOW}Golang not found. Install...${NC}"
+    if ! command -v wget &> /dev/null; then
+        echo "Installing wget..."
+        sudo apt-get update
+        sudo apt-get install -y wget
+    fi
+
+    echo "Downloading Go ${GO_VERSION} for Linux..."
+    wget https://go.dev/dl/go${GO_VERSION}.linux-amd64.tar.gz
+
+    echo "Removing old Go installation if exists..."
+    sudo rm -rf /usr/local/go
+
+    echo "Installing Go..."
+    sudo tar -C /usr/local -xzf go${GO_VERSION}.linux-amd64.tar.gz
+
+    if [[ ":$PATH:" != *":/usr/local/go/bin:"* ]]; then
+        echo "Adding Go to PATH..."
+        echo 'export PATH=$PATH:/usr/local/go/bin' >> ~/.bashrc
+        source ~/.bashrc
+    fi
+
+    rm go${GO_VERSION}.linux-amd64.tar.gz
+    go version
+else
+    echo -e "Golang already install."
+fi
 
 cd "$HOME"
 make build
